### ISSUE TITLE
Session.query() is untyped

### ISSUE THREAD

**Issue by cblegare** [dropbox/sqlalchemy-stubs#138]
Hello everyone.  First, thank for these stubs.

I am playing with mypy and sqlalchemy and ran into this issue.  I might have something wrong

```python
Base = sqlalchemy.ext.declarative.declarative_base()

class Bunny(Base):
    __tablename__ = "bunny"
    id = Column(Integer, primary_key=True)
    color = Column(String)

# create engine, etc.
session: sqlalchemy.orm.session.Session = cast(sqlalchemy.orm.session.Session, Session())
query = cast(sqlalchemy.orm.query.Query, session.query(Bunny))
bunnies = session.query(Bunny).all()
```

Which yield

```
easter.py:19: error: Call to untyped function "query" in typed context
easter.py:20: error: Call to untyped function "query" in typed context
```

When I manually edit the stubs to add type annotation to the "query" function, [here](https://github.com/dropbox/sqlalchemy-stubs/blob/master/sqlalchemy-stubs/orm/session.pyi#L63), it silences the error.

Is the issue simply that return types have not been added yet?  Will they be in the future?  I guess my question is more about the lifecycle of stubs projects.

**Comment by JukkaL** [comment]
I think that `query` may be too dynamic to enable a precise annotation. The stubs are also not complete by any means.

We accept PRs. At the moment we aren't actively improving the stubs ourselves.

**Comment by cblegare** [comment]
Thank you @JukkaL 

I found #121 and #81 opened on this topic.

Also, this issue is listed at #3

So I thought I could have a look to help with these and I was not able to get the tests running.

I read the readme, checked out the repo, inited submodules, made a venv, installed the package and dev requirements.

I was not able to run the tests properly:

```
 $ python -m pytest -vvvvvv
======== test session starts ========
platform linux -- Python 3.7.5, pytest-5.3.4, py-1.8.1, pluggy-0.13.1 -- /home/me/sqlalchemy-stubs/.venv/bin/python
cachedir: .pytest_cache
rootdir: /home/me/sqlalchemy-stubs, inifile: pytest.ini, testpaths: test
plugins: cov-2.8.1, xdist-1.31.0, forked-1.0.2
[gw0] linux Python 3.7.5 cwd: /home/me/sqlalchemy-stubs
[gw1] linux Python 3.7.5 cwd: /home/me/sqlalchemy-stubs
[gw2] linux Python 3.7.5 cwd: /home/me/sqlalchemy-stubs
[gw3] linux Python 3.7.5 cwd: /home/me/sqlalchemy-stubs
[gw0] Python 3.7.5 (default, Dec 13 2019, 11:49:27)  -- [GCC 7.4.0]
[gw1] Python 3.7.5 (default, Dec 13 2019, 11:49:27)  -- [GCC 7.4.0]
[gw2] Python 3.7.5 (default, Dec 13 2019, 11:49:27)  -- [GCC 7.4.0]
[gw3] Python 3.7.5 (default, Dec 13 2019, 11:49:27)  -- [GCC 7.4.0]
gw0 [53] / gw1 [53] / gw2 [53] / gw3 [53]
scheduling tests via LoadScheduling
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/me/sqlalchemy-stubs/.venv/lib/python3.7/site-packages/_pytest/main.py", line 197, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/me/sqlalchemy-stubs/.venv/lib/python3.7/site-packages/_pytest/main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/me/sqlalchemy-stubs/.venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/me/sqlalchemy-stubs/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/me/sqlalchemy-stubs/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/me/sqlalchemy-stubs/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/me/sqlalchemy-stubs/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/me/sqlalchemy-stubs/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/me/sqlalchemy-stubs/.venv/lib/python3.7/site-packages/xdist/dsession.py", line 112, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/home/me/sqlalchemy-stubs/.venv/lib/python3.7/site-packages/xdist/dsession.py", line 135, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/home/me/sqlalchemy-stubs/.venv/lib/python3.7/site-packages/xdist/dsession.py", line 177, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('test/testsql.py::SQLDataSuite::testColumnFieldsInferredInstance', <WorkerController gw2>)
INTERNALERROR> assert not 'test/testsql.py::SQLDataSuite::testColumnFieldsInferredInstance'

======== no tests ran in 0.90s ========
```

At each run, a random item crashed.  Since I am not familiar with pytest plugins used (xdist, fork), I stopped investigating after some time.

In case something obvious is missing and you can give me a cue I'd gladly look into it.  Otherwise, I thought it could be useful to share difficulties I had contributing.  If this looks like a bug to you, I'll create a separate issue.
