### ISSUE TITLE
sqlmypy is broken with mypy 0.750+

### ISSUE THREAD

**Issue by a-recknagel** [dropbox/sqlalchemy-stubs#145]
Given the sample code on [how to create a class with sqlalchemy](https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/basic_use.html#basic-use):

```python
from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class SomeClass(Base):
    __tablename__ = 'some_table'
    id = Column(Integer, primary_key=True)
    name = Column(String(50))
```
and the sqlmypy plugin switched on in mypy.ini:

```ini
[mypy]
plugins = sqlmypy
```
Running mypy on said code fails with an internal error in the line that calls `declarative_base`:

```
$ mypy mp.py --show-traceback
mp.py:4: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.770+dev.20f7f2dd71c21bde4d3d99f9ab69bf6670c7fa03
Traceback (most recent call last):
  File "/home/dev/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/main.py", line 89, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/build.py", line 180, in build
    result = _build(
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/build.py", line 249, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/build.py", line 2649, in dispatch
    process_graph(graph, manager)
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/build.py", line 2956, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/build.py", line 3049, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/semanal_main.py", line 78, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/semanal_main.py", line 199, in process_top_levels
    deferred, incomplete, progress = semantic_analyze_target(next_id, state,
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/semanal_main.py", line 326, in semantic_analyze_target
    analyzer.refresh_partial(refresh_node,
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/semanal.py", line 350, in refresh_partial
    self.refresh_top_level(node)
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/semanal.py", line 361, in refresh_top_level
    self.accept(d)
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/semanal.py", line 4679, in accept
    node.accept(self)
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/nodes.py", line 1062, in accept
    return visitor.visit_assignment_stmt(self)
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/semanal.py", line 1931, in visit_assignment_stmt
    self.apply_dynamic_class_hook(s)
  File "/home/dev/venv/lib/python3.8/site-packages/mypy/semanal.py", line 2182, in apply_dynamic_class_hook
    hook(DynamicClassDefContext(call, lval.name, self))
  File "/home/dev/venv/lib/python3.8/site-packages/sqlmypy.py", line 193, in decl_info_hook
    add_metadata_var(ctx.api, info)
  File "/home/dev/venv/lib/python3.8/site-packages/sqlmypy.py", line 133, in add_metadata_var
    add_var_to_class('metadata', typ, info)
  File "/home/dev/venv/lib/python3.8/site-packages/sqlmypy.py", line 95, in add_var_to_class
    var._fullname = info.fullname() + '.' + name
TypeError: 'str' object is not callable
mp.py:4: : note: use --pdb to drop into pdb
```
It still works in 0.740, but fails on every version from 0.750 upwards until the current master, which I used to generate the traceback above.

**Comment by a-recknagel** [comment]
Funny thing, I was debugging this for a good hour. And right when I post this, I remember that I didn't try updating `sqlalchemy-stubs`. Turns out it's only broken on `0.2` and fixed in `0.3`. Oh well, maybe this most short lived issue will help some poor soul stumbling over it from google.
