### ISSUE TITLE
AssertionError in column_hook

### ISSUE THREAD

**Issue by cromefire** [dropbox/sqlalchemy-stubs#77]
sqlachemy version: `1.2.17`
mypy version: `0.670`
```
<path to project>/.venv/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/information_schema.py:59: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.670
Traceback (most recent call last):
  File "<path to project>/build.py", line 46, in <module>
    lint()
  File "<path to project>/build.py", line 36, in lint
    "--show-traceback"
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/main.py", line 91, in main
    res = build.build(sources, options, None, flush_errors, fscache)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/build.py", line 162, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/build.py", line 217, in _build
    graph = dispatch(sources, manager)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/build.py", line 2360, in dispatch
    process_graph(graph, manager)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/build.py", line 2660, in process_graph
    process_stale_scc(graph, scc, manager)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/build.py", line 2767, in process_stale_scc
    graph[id].type_check_first_pass()
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/build.py", line 1919, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checker.py", line 282, in check_first_pass
    self.accept(d)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/nodes.py", line 969, in accept
    return visitor.visit_assignment_stmt(self)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checker.py", line 1709, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None, s.new_syntax)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checker.py", line 1828, in check_assignment
    in_final_declaration=inferred.is_final,
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 3188, in accept
    typ = node.accept(self)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/nodes.py", line 1446, in accept
    return visitor.visit_call_expr(self)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 244, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 314, in visit_call_expr_inner
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname, object_type)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 658, in check_call_expr_with_callee_type
    object_type=object_type)[0]
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 695, in check_call
    object_type)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 780, in check_callable_call
    callee, args, arg_kinds, formal_to_actual)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 873, in infer_arg_types_in_context
    res[ai] = self.accept(args[ai], callee.arg_types[i])
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 3188, in accept
    typ = node.accept(self)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/nodes.py", line 1446, in accept
    return visitor.visit_call_expr(self)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 244, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 314, in visit_call_expr_inner
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname, object_type)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 658, in check_call_expr_with_callee_type
    object_type=object_type)[0]
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 695, in check_call
    object_type)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 802, in check_callable_call
    callable_name, object_type, context)
  File "<path to project>/.venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 574, in apply_function_plugin
    callee.ret_type, formal_arg_exprs, context, self.chk))
  File "<path to project>/.venv/lib/python3.6/site-packages/sqlmypy.py", line 257, in column_hook
    assert len(ctx.default_return_type.args) == 1
AssertionError: 
```

**Comment by ilevkivskyi** [comment]
Thanks for reporting and sorry for the crash! Do you have a way to reproduce this? Maybe you can show some simplified code that triggers this?

**Comment by vitalbmcdonald** [comment]
I have also ran into this issue, here is a minimal case to reproduce the issue.

Setup:

To keep pathing simple, this was done in /temp
1. create venv, `python -m venv .venv`
2. activate venv, `source .venv/bin/activate`
3. install packages, `pip install sqlalchemy mypy sqlalchemy-stubs`
4. create my_file.py:
```
import sqlalchemy
```
5. create mypy.ini:
```
[mypy]
plugins = sqlmypy
mypy_path = /temp/.venv/lib/python3.7/site-packages/ 
```
7. run test, `mypy my_file.py`

Produces:

```
/temp/.venv/lib/python3.7/site-packages/sqlalchemy/dialects/mssql/information_schema.py:60: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.720
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3404, in accept
  File "mypy/nodes.py", line 1527, in accept
  File "mypy/checkexpr.py", line 234, in visit_call_expr__ExpressionVisitor_glue
  File "mypy/checkexpr.py", line 243, in visit_call_expr
  File "mypy/checkexpr.py", line 315, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 670, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 728, in check_call
  File "mypy/checkexpr.py", line 835, in check_callable_call
  File "mypy/checkexpr.py", line 573, in apply_function_plugin
  File "/temp/.venv/lib/python3.7/site-packages/sqlmypy.py", line 296, in column_hook
    assert len(ctx.default_return_type.args) == 1
AssertionError: 
/temp/.venv/lib/python3.7/site-packages/sqlalchemy/dialects/mssql/information_schema.py:60: : note: use --pdb to drop into pdb
```

Env:
OS: Ubuntu 18.04.3
python: 3.7.4
pip list
```
mypy              0.720  
mypy-extensions   0.4.1  
pip               19.0.3 
setuptools        40.8.0 
SQLAlchemy        1.3.8  
sqlalchemy-stubs  0.2    
typed-ast         1.4.0  
typing-extensions 3.7.4  
```

Notes:
If you leave out the mypy_path setting in mypy.ini, it passes just fine. 
If you leave out the plugins setting in mypy.ini, it passes just fine. 
If you leave out the mypy.ini, it passes just fine. 

The reason for pointing at site-packages is to solve issues with modules not being found. 
Errors like: `error: Cannot find module named 'example'`

**Comment by vitalbmcdonald** [comment]
Interestingly, if you leave off the trailing `/` in `mypy_path` setting, mypy complains and exits with error code 1.

Using setup from above:
1. mypy.ini:
```
[mypy]
plugins = sqlmypy
mypy_path = /temp/.venv/lib/python3.7/site-packages
```
2. run `mypy my_file.py`

Produces:
```
/temp/.venv/lib/python3.7/site-packages is in the MYPYPATH. Please remove it.
```

I don't think its actually relevant, but there you go.

**Comment by ilevkivskyi** [comment]
Ouch, adding `site-packages` to `MYPYPATH` is actually a bad idea, it can break many things, that error doesn't explain why, you can read more details [here](https://mypy.readthedocs.io/en/latest/running_mypy.html#how-mypy-handles-imports). I am going to make a PR for mypy to make tighten this.

**Comment by vitalbmcdonald** [comment]
As an FYI to those adding site-packages due to missing import errors, I had to make the package I was developing PEP 561 compatible, as [documented by mypy](https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages).
